config/urls.py
from debug_toolbar.toolbar import debug_toolbar_urls
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from config import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('home.urls')),
    path('', include('contact.urls')),
    path('products/', include('product.urls')),

] + debug_toolbar_urls()

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

contact/urls.py
from django.urls import path

from . import views

app_name = 'contact'

urlpatterns = [
    path('contact/', views.ContactView.as_view(), name='contact'),
    
]

home/urls.py
from django.urls import path

from . import views

app_name = 'home'

urlpatterns = [
    path('', views.home, name='home'),
]

product/urls.py
from django.urls import path

from . import views

app_name = 'product'

urlpatterns = [
    path('', views.ProductListView.as_view(), name='product_list'),
    path('<int:pk>', views.ProductDetailView.as_view(), name='product_detail'),
    path('add_product/', views.ProductCreateView.as_view(), name='add_product'),
]

contact/models.py
from django.db import models

class Contact(models.Model):
    name = models.CharField(max_length=25)
    email = models.EmailField()
    phone = models.CharField(max_length=15)
    message = models.TextField()

    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return self.message[:10] + ('...' if len(self.message) > 10 else '')

product/models.py
from django.db import models
from django.utils.text import slugify


class Modified(models.Model):
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        abstract = True


class Product(Modified):
    name = models.CharField(max_length=100) # <input type='text'>
    description = models.TextField(default="", blank=True) # <textarea></textarea>
    price = models.DecimalField(max_digits=6, decimal_places=2) # <input type='number'>
    stock_count = models.IntegerField(help_text="How many items are currently in stock")
    sku = models.CharField(max_length=20, verbose_name="Stock Keeping Unit")
    slug = models.SlugField(unique=True, blank=True)

    def __str__(self):
        return self.name

    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.name)
        return super().save(*args, **kwargs)

class ProductImage(models.Model):
    image = models.ImageField(upload_to='product_images') # Pil (Pillow)
    product = models.ForeignKey('Product', on_delete=models.CASCADE, related_name='images')

    def __str__(self):
        return str(self.image)

class Category(models.Model):
    name = models.CharField(max_length=20)
    products = models.ManyToManyField('Product', related_name='categories')

    def __str__(self):
        return self.name

    class Meta:
        verbose_name_plural = 'Categories'
        verbose_name = 'Product Category'
        ordering = ('name',)

contact/forms.py
from django import forms


class ContactForm(forms.Form):
    name = forms.CharField()
    email = forms.EmailField()
    phone = forms.CharField()
    message = forms.CharField(widget=forms.Textarea)

contact/views.py
from django.urls import reverse_lazy
from django.views.generic import FormView
from . import forms
from . import models


class ContactView(FormView):
    template_name = 'contact/contact.html'
    form_class = forms.ContactForm
    success_url = reverse_lazy('home:home')

    def form_valid(self, form):
        models.Contact.objects.create(**form.cleaned_data)
        return super().form_valid(form)

home/views.py
from django.shortcuts import render

def home(request):
    return render(request, 'home/home.html')

product/views.py
from django.http import Http404
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import ListView, DetailView, CreateView

from . import models

class ProductListView(ListView):
    model = models.Product
    template_name = 'product/products.html'
    context_object_name = 'products'

class ProductDetailView(DetailView):
    model = models.Product
    template_name = 'product/product.html'
    context_object_name = 'product'

class ProductCreateView(CreateView):
    model = models.Product
    fields = ('name', 'description', 'price', 'stock_count', 'sku', 'slug')
    template_name = 'product/product_form.html'
    success_url = reverse_lazy("product:product_list")

contact/templates/contact/contact.html
{% extends 'base.html' %}

{%  block title %}ContactPage{% endblock %}

{% block container %}

  <h1>Contact</h1>

{%  endblock %}

home/templates/home/home.html
{% extends 'base.html' %}

{%  block title %}HomePage{% endblock %}
{% block container %}

  <h1>Alegrosz</h1>

{%  endblock %}

product/templates/product/product.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Product {{ product.name }}{% endblock %}

{% block container %}

    <div class="card mb_5">
        {% if product.images.first %}
            <img src="/media/{{ product.images.first }}" class="card-img-top" alt="{{ product.name }}">
        {%  else %}
            <img src="{% static 'images/no_image.png' %}" class="card-img-top" alt="{{ product.name }}">
        {% endif %}
        <div class="card-body">
            <h5 class="card-title">{{ product.name }}</h5>
            <p class="card-text">{{ product.description }}</p>
        </div>
          <ul class="list-group list-group-flush">
            <li class="list-group-item">Price ${{ product.price }}</li>
            <li class="list-group-item">Stock keeping unit: {{ product.sku }}</li>
            <li class="list-group-item">Stock count: {{ product.stock_count }}</li>
          </ul>
          <div class="card-body">
            <a href="{% url 'product:product_list' %}" class="card-link">Back</a>
          </div>
    </div>

{% endblock %}

product/templates/product/product_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}

{% block title %}Create Product{% endblock %}

{% block container %}
    <form action="" method="post">
        {% csrf_token %}
            {{ form|crispy }}
        <input class="btn btn-success" type="submit" value="Add Product">
    </form>
{% endblock %}

product/templates/product/products.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Product List{% endblock %}

{% block container %}

    <h1>Product List</h1>

    <div class="row row-cols-1 row-cols-md-3 g-4">
        {% for product in object_list %}
            <div class="col">
                <div class="card">
                {% if product.images.first %}
                	<img src="/media/{{ product.images.first }}" class="card-img-top" alt="{{ product.name }}">
                {% else %}
                    <img src="{% static 'images/no_image.png' %}" class="card-img-top" alt="{{ product.name }}">
                {% endif %}
                <div class="card-body">
                    <h5 class="card-title">{{ product.name }}</h5>
                    {% if product.description|length > 50 %}
                        <p class="card-text">{{ product.description|slice:"50" }}...</p>
                    {% else %}
                        <p class="card-text">{{ product.description }}</p>
                    {% endif %}
                    <p class="card-text">
                        Price: ${{ product.price }}
                    </p>
                    <a href="{% url 'product:product_detail' pk=product.pk %}" class="btn btn-primary">Show details</a>
                </div>
                </div>
            </div>
        {% endfor %}
    </div>


{% endblock %}

templates/base.html
{% load static %}

<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>💰💰💰 Alegrosz - {% block title %}{% endblock %}</title>

    {% block styles %}
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/main.css' %}">
    {% endblock %}

    {% block scripts %}
        <script src="{% static 'scripts/bootstrap.bundle.min.js' %}" async defer></script>
    {% endblock %}

</head>
<body>

{% block header %}{% endblock %}

{% include 'partials/nav.html' %}

<div class="container mt-3">
    <div class="row">
        <div class="col-12 col-md-8">
            {% block container %}{% endblock %}
        </div>
    </div>

</div>

</body>
</html>

templates/partials/nav.html
{% load static %}

<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <a class="navbar-brand" href="{% url 'home:home' %}">
        <img class="logo" src="{% static 'images/logo.svg' %}" alt="Logo Alegrosz">
    </a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarNav">
      <ul class="navbar-nav">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="{% url 'home:home' %}">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'product:product_list' %}">Products</a>
        </li>
          <li class="nav-item">
          <a class="nav-link" href="{% url 'product:add_product' %}">Add Product</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'contact:contact' %}">Contact</a>
        </li>
      </ul>
    </div>
  </div>
</nav>